### ISSUE TITLE
Binding to a event-handlers does not scope `this` as the view-model.

### ISSUE THREAD

**Issue by m-andrew-albright** [froala/aurelia-froala-editor#21]
I was trying to do some things on the 

in my view:

```
<aurelia-froala value.two-way="response.text" config.bind="config" 
  event-handlers.bind="{input: handleInput}"></aurelia-froala>
```

in my view-model:

```
export class TextResponse {
  /* ... */
  handleInput() {
    this.response.isValid = this.response.text && this.response.text.trim() !== '';
  }
}
```

Unfortunately, `this` is scoped to the froala object.  This does not fit the Aurelia convention; so if there is a recommended way to handle this please let me know.

**Comment by henning-krause** [comment]
I'm using an autobind decorator on such methods... that usually works.

**Comment by m-andrew-albright** [comment]
@henning-krause Would you elaborate a little?  I'm not familiar with an autobind decorator - is it a part of the aurelia framework?
