### ISSUE TITLE
How to set up a global default config?

### ISSUE THREAD

**Issue by m-andrew-albright** [froala/aurelia-froala-editor#22]
In your examples, you show how to bind to a configuration like so: 
```
<aurelia-froala value.two-way="value"
    config.bind="{
        toolbarButtons: ['redo' , '|', 'fontFamily', '|', 'fontSize', '|', 'paragraphFormat', 'color', '|', 'bold', 'italic', 'underline', 'strikethrough', 'subscript', 'superscript', 'outdent', 'indent', 'clearFormatting', 'insertTable', 'html'],
        toolbarButtonsMD: ['redo' , '|', 'fontFamily', '|', 'fontSize', '|', 'paragraphFormat', 'color'],
        toolbarButtonsSM: ['redo' , '|', 'fontFamily', '|', 'fontSize', '|', 'paragraphFormat', 'color'],
        toolbarButtonsXS: ['redo' , '|', 'fontFamily', '|', 'fontSize', '|', 'paragraphFormat', 'color'],
        fontFamilySelection: true,
        fontSizeSelection: true
    }">
</aurelia-froala>
```

Let's say I want this exact same config for each froala editor throughout my entire application.  Is there a way I can set this up in the plug-in configuration in main.js, or anywhere else?

**Comment by allencoded** [comment]
yep main.js can do that. I put it there because when I asked elroy it was a WIP on what was going to be needed. If you put them in the main.js it will use that. If you put them there it will override main I believe.

**Comment by m-andrew-albright** [comment]
Can you show an example?  I see where you can add certain things such as icons, languages, plug-ins; but I didn't see how you would set the actual config itself.

**Comment by stefanneculai** [comment]
The best way would be to put it in your main.js files after you include the editor JS files.  You can use $.FroalaEditor.DEFAULTS for that.
