### ISSUE TITLE
Accessing changed objects

### ISSUE THREAD

**Issue by allencoded** [froala/aurelia-froala-editor#3]
I am trying to access the changed bound object from aurelia-froala. 

`<aurelia-froala value.bind="data.body"></aurelia-froala>`

Once the page loads it does seem to grab my saved value from data.body. I then type in the editor and press the save button on my page which calls the save() function. In this function I am unable to see the changes from aurelia-froala like as if it isn't two binded.

edit-text.html:
```
<aurelia-froala value.bind="data.body"></aurelia-froala>
<button type="button" class="btn btn-md btn-eb-item" click.delegate="save()">
    Save
</button>
```

edit-text.js:
```
save() {
  console.log(this.data.body); // <- this never changes even though I have changed text in the editor
}
```

**Note**: I also tried
`<aurelia-froala value.two-way="data.body"></aurelia-froala>`

**Comment by stefanneculai** [comment]
@allencoded would it be possible to put together a jsFiddle or maybe send us a zip where to replicate this?

**Comment by florinpopescu** [comment]
It works for me:
```html
  <aurelia-froala value.two-way="data.body">
  </aurelia-froala>
  <button type="button" class="btn btn-md btn-eb-item" click.delegate="save()">
    Save
  </button>
```
```typescript
  constructor() {
    this.data = { 
      body: 'test'
    };
  }
  save() {
    console.log(this.data.body);
  }
```

When the page loads, 'test' value appear. If I type 'test test again' and press save, the output is `<p>test test again</p>`

@allencoded can you clease check if it works for you with the new fix? Download the lib again with `jspm install github:froala/aurelia-froala-editor@master` and include it with `.plugin('froala/aurelia-froala-editor', config => {...});`

**Comment by allencoded** [comment]
Verified working in new version 👍
