### ISSUE TITLE
How do I set my froala license for this plug-in?

### ISSUE THREAD

**Issue by m-andrew-albright** [froala/aurelia-froala-editor#34]
Used to be, I'd call

```
        config.setLicense('MY_LICENSE_KEY');
```

I updated a few versions recently because my team switched to webpack, and we had to (which I resisted updating because this means we lost the `.addDefaltOptions()` (sic) configuration method.  After updating, I am seeing the [Unlicensed Froala Editor] being displayed on all our froala editors throughout the system.  So has this changed?  The readme.md file removed the instruction on how to do this as well.

**Comment by stefanneculai** [comment]
You should set it as an option when initializing the editor. Global config was removed for now: https://github.com/froala/aurelia-froala-editor/blob/master/README.md#options

**Comment by m-andrew-albright** [comment]
What is the property name in the config object?  I couldn't find it in the docs.

**Comment by stefanneculai** [comment]
The name for the option is `key`.

**Comment by m-andrew-albright** [comment]
Thank you.  That worked.
