### ISSUE TITLE
Css file loading for aurelia-cli

### ISSUE THREAD

**Issue by frakevich** [froala/aurelia-froala-editor#35]
Hi, I am using aurelia-cli, no webpack.  Trying to include the froala css file, but the methods in the example don't work.  Could you please provide an example for my case? 
I tried adding: import 'text!froala-editor/css/froala_editor.pkgd.min.css';  to main.js, but had an issue with a loader.  Tried adding: <require from='../node_modules/froala-editor/css/froala_editor.pkgd.min.css'></require> to app.html, no effect.
This is my aurelia.json file:
{
            "name": "aurelia-froala-editor",
            "path": "../node_modules/aurelia-froala-editor/dist/amd",
            "main": "index"
 } 

Do you have any advice?

Thank you!

**Comment by stefanneculai** [comment]
Please follow the new instructions: https://github.com/froala/aurelia-froala-editor#with-aurelia-cli.
