### ISSUE TITLE
Unable to install via JSPM

### ISSUE THREAD

**Issue by mreiche** [froala/aurelia-froala-editor#36]
`jspm install aurelia-froala-editor`
>err  Installing npm:aurelia-froala-editor@2.5.1, no version match for npm:froala-editor@>=2.5.1

**Comment by gbreeze** [comment]
fix: https://github.com/gbreeze/aurelia-froala-editor/commit/c5f23056ee8f1ced1f9a7825e7770d5d5183c2c1

**Comment by stefanneculai** [comment]
@gbreeze could you please make a PR? Thank you.

**Comment by DitlevHB** [comment]
I'm still getting
Warn: Installing github:gbreeze/aurelia-froala-editor@2.5.1, no version match for npm:froala-editor@>=2.5.1

**Comment by gbreeze** [comment]
hi, you have to use `github:gbreeze/aurelia-froala-editor@master`

**Comment by mreiche** [comment]
I'm closing this unconfirmed. We've implemented a aurelia component by our own, sorry.
