### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by gbreeze** [froala/aurelia-froala-editor#37]
Hi guys,

is there some typescript support? I'm not able to get the 'import' to work. `froala.default();` is always undefined.

```
import * as froala from 'froala-editor/js/froala_editor.pkgd.min.js';

...

froala.default();
```

best regards

**Comment by gbreeze** [comment]
I got this working by doing following:

```
import 'font-awesome/css/font-awesome.css!'
import 'froala-editor/css/froala_editor.pkgd.min.css!'
import froala = require('froala-editor/js/froala_editor.pkgd.min')
froala() //or: froala(jQuery)


...
//froala.default() <-- not working/not needed?
aurelia.use.plugin('aurelia-froala-editor')
```

**Comment by rjonnalagadda** [comment]
does that above fix works for JSPM installation too?

**Comment by gbreeze** [comment]
Yes, jspm/typescript

**Comment by rjonnalagadda** [comment]
i tried the above solution but in main.ts it still cant find the path.. i am getting TS2307 error.

![image](https://cloud.githubusercontent.com/assets/16947139/25356716/3f2ca51a-2909-11e7-81ec-8b2f991c2dec.png)
