### ISSUE TITLE
jspm installer error

### ISSUE THREAD

**Issue by duranmg** [froala/aurelia-froala-editor#4]
The jspm intaller adds an entry to the config.js

> "aurelia-froala-editor": "github:froala/aurelia-froala-editor@2.3.2",`

but the readme.md has the plugin looking for "aurelia-froala"  

> .plugin('aurelia-froala', config => {})

`Error loading http://localhost:9000/dist/aurelia-froala.js`

either the documentation needs to change or the config.js entry should be changed.

**Comment by duranmg** [comment]
Once I fix the plug-in name...i get this error message from the browser

> Error loading http://localhost:9000/dist/aurelia-i18n.js as "aurelia-i18n" from http://localhost:9000/jspm_packages/github/froala/aurelia-froala-editor@2.3.2/aurelia-froala.js

**Comment by allencoded** [comment]
You need to install aurelia-i18n via jspm as well that made it go away for me.

**Comment by duranmg** [comment]
Yeah I figured that out but when I did I got another error....  

> `Potentially unhandled rejection [3] (SystemJS) Error: Out of stack space`

**Comment by florinpopescu** [comment]
@duranmg , @allencoded. I updated the lib. Can you please have a look again and see if those errors are fixed? 
Please try with `jspm install github:froala/aurelia-froala-editor@master` and include it with `.plugin('froala/aurelia-froala-editor', config => {...});`

Thanks :)

**Comment by antonioj-mattos** [comment]
@florinpopescu 

After you fixed the css error described in #6 I was getting a runtime error due to a misconfiguration

```shell
Request URL:http://localhost:5000/dist/froala/aurelia-froala-editor.js
Request Method:GET
Status Code:404 Not Found
```

However, with the merge of #8 #9 the problem went away. Everything is working as it should, at least for me.

**Comment by florinpopescu** [comment]
@antonioj-mattos That's great! :smiley:

**Comment by stefanneculai** [comment]
Closing this one. In case you have any problems, please leave a comment.
