### ISSUE TITLE
Froala doesn't focus when `initOnClick` is set

### ISSUE THREAD

**Issue by burnhamrobertp** [froala/aurelia-froala-editor#41]
Similar to [this issue](https://github.com/froala/react-froala-wysiwyg/issues/34), the aurelia froala doesn't appear to focus the froala editor after `initOnClick` for **mobile devices**. `initOnClick` does work normally for desktop browsers. This can be reproduced in chrome with responsiveness mode turned on in the dev tools.

There are no errors in the console, but you must "tap" on the input twice in order to provide input. Once to initialize Froala and another to give the froala editor focus. Removing all plugins, event handling, etc. does not change the behavior:

`<froala-editor config.bind="{ initOnClick: true }"></froala-editor>`

**Comment by stefanneculai** [comment]
Thanks for reporting this @burnhamrobertp. It would be amazing if you could check on real devices as well.

**Comment by burnhamrobertp** [comment]
I tested this on Chrome on a S8 and the behavior is the same as I described above.

**Comment by stefanneculai** [comment]
This should be fixed on the latest version.
