### ISSUE TITLE
contentChanged event not caught, value not updating

### ISSUE THREAD

**Issue by smajl** [froala/aurelia-froala-editor#42]
Seems like Froala is properly firing `contentChanged` event but it's never caught here:
https://github.com/froala/aurelia-froala-editor/blob/master/src/froala-editor.js#L59
so value is not updating, only on focus/blur cycle.

So I need to manually do it myself with
```
...on('froalaEditor.contentChanged', (e, editor) => { this.value = editor.html.get(); })...
```
Interesting thing is, native Javascript `addEventListener` does not work...

Tried to provide Gist, but did not manage to create a more sophisticated one with stuff like `aurelia.use.plugin(...)`. Do you have a template maybe?

**Comment by stefanneculai** [comment]
@smajl it appears the problem is from having that `,` there. Could you please make a PR to remove it?

**Comment by Lampy09** [comment]
I've hit the same problem and created a PR (https://github.com/froala/aurelia-froala-editor/pull/45)
