### ISSUE TITLE
table cell popup menu not working

### ISSUE THREAD

**Issue by arnonuem** [froala/aurelia-froala-editor#44]
In the froala editor when a table cell is clicked then there is an additional popup which shows some options regarding to cell adjustments.

Here is an example: [context menu](https://www.froala.com/wysiwyg-editor/examples/table-cell-styles)

When i click into the aurelia port of this editor i dont get this context menu :(

Could you please fix this?

But thanks for the aurelia port so far.

**Comment by stefanneculai** [comment]
@arnonuem please make sure you include the `froala-editor/js/froala_editor.pkgd.min` file.

**Comment by arnonuem** [comment]
Why have you closed this ticket?
I have this included the mid file already but it is not working.

![grafik](https://user-images.githubusercontent.com/15833875/35965773-37a198a4-0cbc-11e8-9938-bebf1fb42186.png)

**Comment by stefanneculai** [comment]
@arnonuem could you please send us a link to the page where you have this problem?
