### ISSUE TITLE
Update aurelia-binding dependency

### ISSUE THREAD

**Issue by Sayan751** [froala/aurelia-froala-editor#47]
This package uses `aurelia-binding@^1.0.0`, however, the latest version is `2.1.4`. Please update the dependency to avoid specifying alias in webpack configuration.

Additionally, this package declares a dependency on `aurelia-dependency-injection`, though never uses it directly. On the other hand, it uses `aurelia-framework`, but don't specify `aurelia-framework` as dependency in `package.json`.

**Comment by stefanneculai** [comment]
@Sayan751 do you think you could make a PR for that? Thanks in advance.

**Comment by Sayan751** [comment]
@stefanneculai Will gladly do that. The absence of tests had stopped me from doing that. But I can test it against my project, I guess. Give me some time, I will get back to you.
