### ISSUE TITLE
Locale change is not reflected out of the box

### ISSUE THREAD

**Issue by Sayan751** [froala/aurelia-froala-editor#49]
Changing locale does not change the tooltips automatically. Considering it is an aurelia plugin, locale change should be supported out of the box leveraging aurelia-i18n.

As a work around, I can capture the VM reference,

```html
    <froala-editor view-model.ref="aureliaFroalaEditor" config.bind="config" ...></froala-editor>
```

and use it from my VM on locale change.

```typescript
private aureliaFroalaEditor: FroalaEditor;
private currentLocale: string;

constructor(i18n: I18N, ea: EventAggregator, ...) {
    ea.subscribe("i18n:locale:changed", ({ newValue }) => {
        this.currentLocale = newValue;            
        // do the gymnastic after a little delay
        return new Promise((resolve) => {
            setTimeout(() => {
                this.aureliaFroalaEditor.tearDown();
                this.aureliaFroalaEditor.tearUp();
                resolve();
            }, 1);
        });
    });
}

@computedFrom( "currentLocale")
private get config(): any {
    return { language: this.currentLocale, ... };
}
```
But, this should have been encapsulated in `froala-editor` custom element itself. The biggest downside of the code shown above is if the signatures of `tearDown`/`tearUp` changes, it will be a potentially breaking change for me.

**Comment by Geet06** [comment]
@stefanneculai in above issue the locale can be changed by-
1.  Importing the language file to which we want to localize 
2. binding the language we want with our editor
```
<froala-editor  view-model.ref="aureliaFroalaEditor" config.bind="tempConfig" ></froala-editor>
```
3. and then passing the required language in js file as
```
this.tempConfig = {
      language: 'de'
    };
```
