### ISSUE TITLE
repeat.for broken after injecting plugin

### ISSUE THREAD

**Issue by webcat12345** [froala/aurelia-froala-editor#51]
### Versions

```
aurelia-framework: 1.1.5
webpack: 3.7.1
```
Please let me know what dependencies do you need more.

#### Install dependency on webpack config project
* `new ModuleDependenciesPlugin({'aurelia-froala-editor': [ './froala-editor' ]}),`
* `.plugin(PLATFORM.moduleName('aurelia-froala-editor'));`
#### Simple `repeat.for` test
`HTML Code`

```
<a repeat.for="item of items">A</a>
<button click.delegate="items.push(1)"></button>

```
`Controller Code`
```
list = [];
```
![ezgif-3-7b7e5703a714](https://user-images.githubusercontent.com/19761422/53259024-e957bb00-3682-11e9-8fd1-52caf5f800bc.gif)

Only **1** item should be added, and yes, that's correct, array has only 1 item. But repeat showing 2 items...

**Comment by stefanneculai** [comment]
At this moment, we do not support having template code inside the editor HTML.
